import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "./_components";

export const metadata: Metadata = {
  title: "WeTradeSolutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary text-white">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
